name: GitHub Actions

on:
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint code with ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - run: npm ci
      - name: Run ESLint
        run: npm run lint

  unit_tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - run: npm ci
      - run: npm run test --if-present

  build:
    name: Build Application
    runs-on: ubuntu-latest
    needs: [lint, unit_tests]
    steps:
      - name: Afficher la date
        run: date
      - name: Afficher le contenu du répertoire courant
        run: ls -l
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - run: npm ci
      - name: Define env vars
        run: |
          echo "VITE_BUILD_DATE=$(date +'%d/%m/%Y %H:%M:%S')" >> $GITHUB_ENV
          echo "VITE_BUILD_AUTHOR=${{ github.actor }}" >> $GITHUB_ENV
          echo "VITE_BRANCH_NAME=${{ github.ref_name }}" >> $GITHUB_ENV
      - run: npm run build
      - name: Protect .env files
        run: |
          cat > dist/.htaccess << EOF
          <Files .env>
            Order allow,deny
            Deny from all
          </Files>
          EOF
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: front-end-build
          path: ./dist

#   migrate:
#     name: Run DB Migration (if any)
#     runs-on: ubuntu-latest
#     needs: build
#     steps:
#       - name: Example migration step
#         run: echo "Run migration script here"